#!/usr/bin/env bash
# Script version 1.0

Args=("$@")

echo -e "Example Application!\n"

echo -e "Home path: $HOME \n\nPWD path: $PWD\n"

for i in "${!Args[@]}"; do
	echo -e "${Args[$i]}"
done

read pause
